### ISSUE TITLE
コンフリクト問題

### ISSUE THREAD

**Issue by hotuta** [JAG-SC/ABC2016SpringClient#11]
自分が担当する開発箇所よりもフォーク元がかなり進んでいて気になったのでフォークしている自分のリポジトリに反映させようとしたのですが、コンフリクトエラーが出て萎えて昨日の進捗はほぼ0で終わりました。
今日中に何とかこの問題を手動で解決するつもりですがどなたか何かいい方法があれば教えて下さい><
(ちなみにとある誰かさんはフォークを取り消してフォークし直すという荒業をしている事が判明したのでそれがベストなんだろうか...。)

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">IntelliJ(AndroidStudio)上でFork元を反映でき無さそうなので嫌々コマンド打ち込んだらコンフリクトだよ</p>&mdash; ほつた@ASUS (@hotu_ta) <a href="https://twitter.com/hotu_ta/status/696347277816778753">2016, 2月 7</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEADとかなんなの？<br>喧嘩売ってるの？</p>&mdash; ほつた@ASUS (@hotu_ta) <a href="https://twitter.com/hotu_ta/status/696346571676340229">2016, 2月 7</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by NewNotMoon** [comment]
コンフリクトを解決してコマンドを再実行して下さい

**Comment by hotuta** [comment]
コマンドでのコンフリクト問題解決を諦め、暫定的に彼と同じようにフォークをし直すことにします。
またコンフリクト問題にぶち当たった時はコマンドで解決出来るでしょう。

**Comment by youkidearitai** [comment]
# git-pullとは

git-pullコマンドは、以下の2つを同時に行っているのと同義である。

```
$ git fetch origin
$ git merge origin/master
```

git-fetchコマンドとは、リポジトリから更新した情報だけを取得するコマンドである。ということを考えると、origin(fork元)のbranchを作ってそこへorigin/masterをmergeしてあげた後にコンフリクトが発生するブランチを作るのが良いのではないかと思われる。

少なくとも、ブランチを切ろうとするべきであると考える。

## 参考サイト
- http://qiita.com/osamu1203/items/cb94ef9da02e1ec3e921
- http://www.backlog.jp/git-guide/stepup/stepup2_7.html

**Comment by NewNotMoon** [comment]
ちがう。fetch+mergeはpullコマンド。

**Comment by youkidearitai** [comment]
修正しました。

**Comment by hotuta** [comment]
@youkidearitai ありがとうございます><
多分それ同様のを何となくコピペしてコマンド実行して失敗したのでまたの時に参考にしてチャレンジしたいと思います。！
