### ISSUE TITLE
デザインのベース案作成

### ISSUE THREAD

**Issue by hotuta** [JAG-SC/ABC2016SpringClient#3]
Wearとmobileのデザインについてここで議論しましょう:laughing:
- [x] ベース案提出 
- [x] レビュー、調整
- [x] ベースデザイン確定 提出(12/26)
## 資料

[12/16 @Yuki014](https://github.com/JAG-SC/ABC2016SpringClient/files/64271/12___16____________.pdf)

**Comment by NewNotMoon** [comment]
マイルストーンは12/26、第6回MTGに設定します。
19日にベース案を提出、その後レビューを通して細部の調整、26日の時点でデザインのベースを確定して下さい。

**Comment by hotuta** [comment]
まずこれについて。

![image](https://cloud.githubusercontent.com/assets/11851747/11847062/f1fb97b8-a45e-11e5-858a-c8750c0e7b12.png)

設定とスタートのボタン位置を入れ替えてスタートを下へ持って行った方が良いかと思いました:sweat_smile:
多分時計を右左どちらに付けるかによると思いますが。

**Comment by NewNotMoon** [comment]
右手かな

**Comment by hotuta** [comment]
装着するのが右手でも左手でもWearの画面下部から人差し指でタッチすると思うのでスタートが上または真ん中なのは何か狙いがあるのかな。
ここは提案してくれた@Yuki014にあえてこうしているのか聞いてみないと:sweat_smile:

**Comment by NewNotMoon** [comment]
短剣の表示は微妙。ディスプレイが小さいので細かい装飾はかえって見づらくなります。
スタート画面は剣とかよりはタイトルロゴを表示して欲しいかなあ。タイトルロゴに剣をふくめるのならOK.

**Comment by NewNotMoon** [comment]
デザイン案としては情報不足ですね。
1. フォント形状、サイズや全体の配色などを具体的に示して下さい。
2. 全体のデザインコンセプトが見えてきません。どういうコンセプトでデザインをまとめるか説明をして下さい｡
3. ペイントソフト等でイメージ画像を作って図示すると尚良しです。

**Comment by Yuki014** [comment]
> hotuta
> スタートと設定の位置に関しては特別な意図はありません。
> それなので入れ替えて良いと思います。
> 
> NewNotMoon
> 1.忙しいのでどうなるかわかりませんができたらミーティングまでに資料にまとめておきます。
> 2.デザインコンセプトとしてはレトロな対戦格闘ゲームといったところです。
> 3.了解しました。

**Comment by hotuta** [comment]
サーバーチームのデザイン案に合流したいと思いますが@Yuki014さんはどうでしょうか。
後で、Slackにサーバーチーム案の画像が上がるみたいですのでそれを含め、UI、ボタン、どこをタップするか来週までに確定させましょ:laughing:

**Comment by NewNotMoon** [comment]
[12-19 サーバーデザイン案(かりな).pdf](https://github.com/JAG-SC/ABC2016SpringClient/files/67476/12-19.pdf)
サーバーチームデザイン案PDFです。

サーバー側のデザインコンセプトに合わせてデザインを決めるか、独自に決めていくか、どちらかになります。
案から進んで、ボタンの配置、背景の詳細等も確定させて下さい。
外丸くんと堀田くん、よろしくお願いします。

**Comment by hotuta** [comment]
本当にどうでもいい話ですがスタートの画像と実際プレイする時の擬人化画像の差が気になります:sweat_smile:

> オノマトペや、実際のモデルの顔を柔らかくすればだいたいなんとかなる。

自分はスタート画像のような擬人化ドロイド君が好きなのでそのままでプレイできればと思いました。

**Comment by Yuki014** [comment]
サーバチームの案に合わせる形で良いと思います。
ところで@hotutaくんのデザイン案が見当たらないのですがどうなったのでしょうか？非常に気になります。

**Comment by Yuki014** [comment]
それと@hotutaくん。
デザイン案詰めるにしても話し合いがしたいので都合のいい時間を教えて下さい

**Comment by Yuki014** [comment]
@hotuta くん本日(12月20日)の23：59までに返事ください

**Comment by hotuta** [comment]
@Yuki014今から外出するので外出先でハングアウトを使って話したいと思いますが大丈夫でしょうか。
ちなみにですが自分のデザイン案はデザインが不得意という事もあってあまり纏まっていない状態です。
個人的にはサーバーチームの@NewNotMoonさんの案がかなり良いのでそれをベースにする感じでUI、どこをタップしたらどうなるのかを確定させてしまいたいと思います。

**Comment by Yuki014** [comment]
@hotuta 大丈夫です。
そちらの都合の良い時にかけてきてください

**Comment by Yuki014** [comment]
@hotuta 正直そろそろ待ちくたびれてきました。
話し合いができる詳細な時間を教えて下さい。

**Comment by Yuki014** [comment]
製作担当
ほつた→タイトル画面
外丸　→勝敗画面、もう一度の画面
