### ISSUE TITLE
drawableにある画像を読み込んでくれない

### ISSUE THREAD

**Issue by hotuta** [JAG-SC/ABC2016SpringClient#6]
drawableフォルダを無理やり作って画像を追加しようとしたところ失敗。
![title539126741](https://cloud.githubusercontent.com/assets/11851747/12372380/4c6e5582-bc97-11e5-99d3-e093c99ddea4.png)

**Comment by NewNotMoon** [comment]
ほつたくんのローカルにプッシュしてリンクして頂いた方が早いかも

**Comment by hotuta** [comment]
そもそも、このプロジェクトファイル全般がなんか色々とおかしい気がするんで真っ更なHello Worldをプッシュしたいです(本音)

**Comment by NewNotMoon** [comment]
そんなことはないと思うのでまずは問題のコードを見せてください…

**Comment by hotuta** [comment]
Android Studioの問題みたいで画像表示については自己解決したので一旦閉じます。
xmlで直指定してあげたらちゃんと表示されました。
